version: 0.1
component: build
timeoutInSeconds: 7200
shell: bash
failImmediatelyOnError: true

env:
  variables:
    HOSTED_AGENT_CONTEXT: "apps/hosted-agent"

steps:
  - type: Command
    name: build-hosted-agent-image
    timeoutInSeconds: 7200
    command: |
      set -euo pipefail

      podman build --platform linux/amd64 -t hosted-agent-image "$HOSTED_AGENT_CONTEXT"

outputArtifacts:
  - name: hosted-agent-image
    type: DOCKER_IMAGE
    location: hosted-agent-image
