version: 0.1
component: build
timeoutInSeconds: 7200
shell: bash
failImmediatelyOnError: true

env:
  exportedVariables:
    - LANGGRAPH_URL
    - LANGGRAPH_DEPLOYMENT_ID

steps:
  - type: Command
    name: deploy-langgraph-agent
    timeoutInSeconds: 7200
    command: |
      . infra/devops-hosted-image-build/scripts/deploy_hosted_application.sh LANGGRAPH
