locals {
  repository_name                     = "${var.repository_name}-${var.resource_suffix}"
  langgraph_repository_name           = "${var.langgraph_repository_name}-${var.resource_suffix}"
  langfuse_repository_name            = "${var.langfuse_repository_name}-${var.resource_suffix}"
  openclaw_repository_name            = "${var.openclaw_repository_name}-${var.resource_suffix}"
  llamaindex_repository_name          = "${var.llamaindex_repository_name}-${var.resource_suffix}"
  hosted_application_display_name     = "${var.hosted_application_display_name}-${var.resource_suffix}"
  hosted_deployment_display_name      = "${var.hosted_deployment_display_name}-${var.resource_suffix}"
  langgraph_application_display_name  = "${var.langgraph_hosted_application_display_name}-${var.resource_suffix}"
  langgraph_deployment_display_name   = "${var.langgraph_hosted_deployment_display_name}-${var.resource_suffix}"
  langfuse_application_display_name   = "${var.langfuse_hosted_application_display_name}-${var.resource_suffix}"
  langfuse_deployment_display_name    = "${var.langfuse_hosted_deployment_display_name}-${var.resource_suffix}"
  openclaw_application_display_name   = "${var.openclaw_hosted_application_display_name}-${var.resource_suffix}"
  openclaw_deployment_display_name    = "${var.openclaw_hosted_deployment_display_name}-${var.resource_suffix}"
  llamaindex_application_display_name = "${var.llamaindex_hosted_application_display_name}-${var.resource_suffix}"
  llamaindex_deployment_display_name  = "${var.llamaindex_hosted_deployment_display_name}-${var.resource_suffix}"
  generated_dir                       = "${path.module}/.terraform/generated"
}
